---
- name: Create {{ item.value.name | default(item.key) }} user
  become: yes
  user:
    comment: "{{ item.value.gecos | default(item.key) }}"
    createhome: "{{ item.value.createhome | default('yes') }}"
    home: "{{ item.value.home | default('/home/' ~ item.key) }}"
    group: "{{ item.value.group | default(omit) }}"
    groups: "{{ item.value.groups | default([ ]) | join(',') | default(omit) }}"
    name: "{{ item.value.name | default(item.key) }}"
    password: "{{ item.value.password | default(omit) }}"
    remove: "{{ 'yes' if item.value.state is defined and item.value.state == 'absent' else 'no' }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
    state: "{{ item.value.state | default(omit) }}"
    system: "{{ item.value.system | default(omit) }}"
    uid: "{{ item.value.uid | default(omit) }}"
  when: (not users_and_groups.whitelist_groups)
    or ( item.value.groups is defined and ( item.value.groups | intersect(users_and_groups.whitelist_groups )))
    or ( item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
  tags:
    - configuration
  register: user_created

- name: Check if {{ item.value.name | default(item.key) }} has password
  shell: passwd --status {{ item.value.name | default(item.key) }} | awk '{ print $2 }' | grep 'NP\|L' > /dev/null
  ignore_errors: yes
  register: user_has_no_password
  changed_when: user_has_no_password.rc > 0
  when: ( user_created is defined and user_created.changed )
    and ( item.value.password is not defined )
    and ( item.value.state is not defined  or item.value.state != "absent" )
  tags:
    - configuration

- name: Reset {{ item.value.name | default(item.key) }}'s locked or absent password
  become: yes
  command: "usermod -p '{{ item.value.password|default()}}' {{ item.value.name | default(item.key) }}"
  when: ( user_created is defined and user_created.changed )
    and ( item.value.password is not defined )
    and ( item.value.state is not defined or item.value.state != "absent" )
    and ( user_has_no_password is defined and user_has_no_password.rc == 0 )
  tags:
    - configuration

- name: Expire new {{ item.value.name | default(item.key) }}'s password to prompt creation
  become: yes
  command: "chage -d 0 {{ item.value.name | default(item.key) }}"
  when: ( user_created is defined and user_created.changed )
    and ( item.value.password is not defined )
    and ( item.value.state is not defined or item.value.state != "absent" )
    and ( user_has_no_password is defined and user_has_no_password.rc == 0 )
  tags:
    - configuration

- name: Update {{ item.value.name | default(item.key) }}'s' home directory permissions
  become: yes
  file:
    group: "{{ item.value.group | default(omit) }}"
    mode: 0750
    owner: "{{ item.value.name | default(item.key) }}"
    path: "{{ item.value.home | default('/home/' ~ item.key) }}"
    state: directory
  when: ( user_created is defined and user_created.changed )
    and (item.value.state is not defined or item.value.state != "absent")
    and (item.value.createhome is not defined or item.value.createhome)
    and (
      (not users_and_groups.whitelist_groups)
      or ( item.value.groups is defined and ( item.value.groups | intersect(users_and_groups.whitelist_groups )))
      or ( item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration

- name: Create .ssh directory in default {{ item.value.name | default(item.key) }} home directory
  become: yes
  file:
    path: "{{ item.value.home | default('/home/' ~ item.key) }}/.ssh"
    owner: "{{ item.value.name | default(item.key) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: 0700
    state: directory
  when: ( user_created is defined and user_created.changed )
    and (users_and_groups.authorized_keys_dir is none)
    and (item.value.state is not defined or item.value.state != "absent")
    and (
      (not users_and_groups.whitelist_groups)
      or ( item.value.groups is defined and ( item.value.groups | intersect(users_and_groups.whitelist_groups )))
      or ( item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration

- name: Copy ssh auth key file to default location
  become: yes
  authorized_key:
    user: "{{ item.value.name | default(item.key) }}"
    key: "{{ lookup('file', item.value.authorized_keys_file) }}"
    manage_dir: yes
  when: (users_and_groups.authorized_keys_dir is none)
    and (item.value.state is not defined or item.value.state != "absent")
    and (item.value.authorized_keys_file is defined)
    and (
      (not users_and_groups.whitelist_groups)
      or (item.value.groups is defined and (item.value.groups | intersect(users_and_groups.whitelist_groups)))
      or (item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration

- name: Copy ssh auth key file to alternate location
  become: yes
  authorized_key:
    user: "{{ item.value.name | default(item.key) }}"
    key: "{{ lookup('file', item.value.authorized_keys_file) }}"
    path: "{{ users_and_groups.authorized_keys_dir ~ '/' ~ }}{{ item.value.name | default(item.key) }}"
    manage_dir: no
  when: (users_and_groups.authorized_keys_dir is not none)
    and (item.value.state is not defined or item.value.state != "absent")
    and (item.value.authorized_keys_file is defined)
    and (
      (not users_and_groups.whitelist_groups)
      or (item.value.groups is defined and (item.value.groups | intersect(users_and_groups.whitelist_groups)))
      or (item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration

- name: Add ssh auth keys to default file
  become: yes
  template:
    src: authorized_keys.j2
    dest: "{{ item.value.home | default('/home/' ~ item.key) }}/.ssh/authorized_keys"
    owner: "{{ item.value.name | default(item.key) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: 0644
  when: ( users_and_groups.authorized_keys_dir is none)
    and (item.value.state is not defined or item.value.state != "absent")
    and (item.value.authorized_keys is defined)
    and (
      (not users_and_groups.whitelist_groups)
      or (item.value.groups is defined and (item.value.groups | intersect(users_and_groups.whitelist_groups)))
      or (item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration

- name: Add ssh auth keys ssh auth key file to alternate file
  become: yes
  template:
    src: authorized_keys.j2
    dest: "{{ users_and_groups.authorized_keys_dir ~ '/' ~ }}{{ item.value.name | default(item.key) }}"
    owner: "{{ item.value.name | default(item.key) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: 0644
  when: (users_and_groups.authorized_keys_dir is not none)
    and (item.value.state is not defined or item.value.state != "absent")
    and (item.value.authorized_keys is defined)
    and (
      (not users_and_groups.whitelist_groups)
      or (item.value.groups is defined and (item.value.groups | intersect(users_and_groups.whitelist_groups)))
      or (item.value.group is defined and item.value.group in users_and_groups.whitelist_groups)
    )
  tags:
    - configuration
